### ISSUE TITLE
Github Badge should link to Action results page

### ISSUE THREAD

**Issue by jbrucker** [GToidZ/ku-polls#49]
If you click on your Github badge it just shows the image in a new tab.

It should open the Github action results page, the way the Codecov badge does.

See for example, <https://github.com/PloyyNK/ku-polls>

**Comment by GToidZ** [comment]
This is fixed in branch [`fix/badge-redirect`](/GToidZ/ku-polls/tree/fix/badge-redirect). Though, as you are grading this repository, I will leave this issue open and will merge my fixes after grading or you will say so.
